### ISSUE TITLE
Logger dan tracer untuk Task service

### ISSUE THREAD

**Issue by hartyanto** [Kelompok-Argon/22-service-observability#2]
1. Ganti bentuk logger dari console.log (dan sejenisnya) dengan winston, yang bentuknya info outputnya console saja, yang bentuknya error output nya console dan file.
2. Implementasi jaeger untuk semua endpoint di service task

**Comment by darczodiac** [comment]
https://stackoverflow.com/questions/36617106/git-gitignore-not-working-with-log-files

```bash
git rm --cached [error_file.log]
```

agar error log bisa ke ignore

**Comment by hartyanto** [comment]
siap mas, hehe
